### ISSUE TITLE
Instance for java.lang.Class not found

### ISSUE THREAD

**Issue by gneuvill** [derive4j/derive4j-fj#1]
- `java.lang.Class` (`Could not find instance of fj.Ord for java.lang.Class`)

**Comment by jbgi** [comment]
Any instance that are not provided by FunctionalJava or the class it self (orphan instances ;)) must be defined locally to the datatype that use it, as a non-private static field or method in its class file.

**Comment by jbgi** [comment]
(Need to add this to the doc)

**Comment by gneuvill** [comment]
> Any instance that are not provided by FunctionalJava or the class it self (orphan instances ;)) must be defined locally to the datatype that use it, as a non-private static field or method in its class file.

Nice !
> (Need to add this to the doc)

Yup. Thanks !
